### PR TITLE
Update action and Ubuntu versions

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Update action and Ubuntu versions.

### CODE REVIEW

**Comment by Snailedlt** [comment]
Has it been tested?

**Comment by Panquesito7** [comment]
> Has it been tested?

Well, the tests passed, so I guess it's kind of tested now? 🤔

**Comment by Snailedlt** [comment]
> > Has it been tested?
> 
> Well, the tests passed, so I guess it's kind of tested now? 🤔

Yeah, looks good :)
The action needs to be updated some more though:
image

**Comment by Panquesito7** [comment]
> > > Has it been tested?
> > 
> > 
> > Well, the tests passed, so I guess it's kind of tested now? 🤔
> 
> Yeah, looks good :) The action needs to be updated some more though: image

Should probably be handled in another PR. I'll investigate, though, after this one's merged.

**Review by Snailedlt — APPROVED** [review]

**Pull request merged**
